import { useState } from "react";
import {
  BarChart3, Loader2, Send, FileDown, Clipboard,
} from "lucide-react";
import { motion, AnimatePresence } from "motion/react";
import { toast } from "../../../lib/toast";
import { copyToClipboard } from "../../../lib/clipboard";
import { type Case } from "../../../lib/mockData";
import { AttendanceEntry, PaymentRecord, OfficeVisit, STORAGE, load, save } from "./operatorTypes";

export function ReportsSection({ u, dc, card, txt, sub, bigBtn, cases, allStaff, addNotification }: any) {
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedReport, setGeneratedReport] = useState<string | null>(null);
  const [reportHistory, setReportHistory] = useState<{ id: string; date: string; type: string }[]>(() => load("emr-op-report-history", []));

  const today = new Date().toISOString().split("T")[0];
  const confirmedIds: string[] = load("emr-op-confirmed", []);
  const attendance: AttendanceEntry[] = load(STORAGE.attendance, []);
  const payments: PaymentRecord[] = load(STORAGE.payments, []);
  const visits: OfficeVisit[] = load(STORAGE.visits, []);
  const todayAttendance = attendance.filter(a => a.date === today);
  const todayPayments = payments.filter(p => p.timestamp.startsWith(today));
  const todayVisits = visits.filter(v => v.timestamp.startsWith(today));

  const generateReport = () => {
    setIsGenerating(true);
    setTimeout(() => {
      const now = new Date();
      const dateStr = now.toLocaleDateString("en-US", { weekday: "long", year: "numeric", month: "long", day: "numeric" });
      const reportEN = `📊 EMERALD VISA CRM — Daily Report\n📅 ${dateStr}\n━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n📁 Cases:\n  • Total Active: ${cases.length}\n  • Confirmed Today: ${confirmedIds.length}\n  • Overdue: ${cases.filter((c: Case) => c.isOverdue).length}\n\n👥 Attendance:\n  • Present: ${todayAttendance.filter(a => a.status === "present").length}\n  • Late: ${todayAttendance.filter(a => a.status === "late").length}\n  • Absent: ${todayAttendance.filter(a => a.status === "absent").length}\n\n💰 Payments:\n  • Recorded Today: ${todayPayments.length}\n  • Total: PKR ${todayPayments.reduce((s, p) => s + p.amount, 0).toLocaleString()}\n\n🏢 Office Visits: ${todayVisits.length}\n\n━━━━━━━━━━━━━━━━━━━━━━━━━━\nGenerated by Computer Operator\nTime: ${now.toLocaleTimeString("en-US")}`;
      const reportUR = `📊 ایمرالڈ ویزا CRM — روزانہ رپورٹ\n📅 ${dateStr}\n━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n📁 کیسز:\n  • کل ایکٹیو: ${cases.length}\n  • آج تصدیق شدہ: ${confirmedIds.length}\n  • تاخیر: ${cases.filter((c: Case) => c.isOverdue).length}\n\n👥 حاضری:\n  • حاضر: ${todayAttendance.filter(a => a.status === "present").length}\n  • دیر سے: ${todayAttendance.filter(a => a.status === "late").length}\n  • غیر حاضر: ${todayAttendance.filter(a => a.status === "absent").length}\n\n💰 ادائیگیاں:\n  • آج درج: ${todayPayments.length}\n  • کل رقم: PKR ${todayPayments.reduce((s, p) => s + p.amount, 0).toLocaleString()}\n\n🏢 آفس وزٹ: ${todayVisits.length}\n\n━━━━━━━━━━━━━━━━━━━━━━━━━━\nکمپیوٹر آپریٹر کی رپورٹ\nوقت: ${now.toLocaleTimeString("en-US")}`;
      setGeneratedReport(u(reportEN, reportUR));
      setIsGenerating(false);
    }, 1500);
  };

  const downloadReport = () => {
    if (!generatedReport) return;
    const blob = new Blob([generatedReport], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url; a.download = `emerald-report-${today}.txt`; a.click();
    const entry = { id: `RPT-${Date.now()}`, date: today, type: "Download" };
    setReportHistory(prev => { const u = [entry, ...prev].slice(0, 30); save("emr-op-report-history", u); return u; });
    toast.success(u("Report downloaded!", "رپورٹ ڈاؤنلوڈ ہو گئی!"));
  };

  const sendWhatsApp = () => {
    if (!generatedReport) return;
    window.open(`https://wa.me/?text=${encodeURIComponent(generatedReport)}`, "_blank");
    addNotification("Daily report sent via WhatsApp", "روزانہ رپورٹ واٹس ایپ سے بھیجی گئی", "report");
    toast.success(u("Opening WhatsApp...", "واٹس ایپ کھل رہا ہے..."));
  };

  const copyReport = () => {
    if (!generatedReport) return;
    copyToClipboard(generatedReport).then(() => toast.success(u("Report copied!", "رپورٹ کاپی ہو گئی!"))).catch(() => toast.error(u("Copy failed", "کاپی نہیں ہو سکا")));
  };

  return (
    <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="space-y-4">
      <motion.button whileTap={{ scale: 0.97 }} onClick={generateReport} disabled={isGenerating}
        className={`${bigBtn} w-full ${isGenerating ? "bg-gray-500 cursor-wait" : "bg-gradient-to-r from-blue-600 to-indigo-600"} text-white`}>
        {isGenerating ? <><Loader2 className="w-5 h-5 animate-spin" /> {u("Generating...", "رپورٹ بن رہی ہے...")}</> : <><BarChart3 className="w-5 h-5" /> {u("Generate Daily Report", "روزانہ رپورٹ بنائیں")}</>}
      </motion.button>

      <div className="grid grid-cols-2 sm:grid-cols-4 gap-2">
        {[
          { label: u("Cases", "کیسز"), value: cases.length, emoji: "📁" },
          { label: u("Confirmed", "تصدیق"), value: confirmedIds.length, emoji: "✅" },
          { label: u("Payments", "ادائیگیاں"), value: todayPayments.length, emoji: "💰" },
          { label: u("Visits", "وزٹ"), value: todayVisits.length, emoji: "🏢" },
        ].map((s, i) => (
          <div key={i} className={`rounded-xl border p-3 text-center ${card}`}>
            <span className="text-xl">{s.emoji}</span>
            <p className={`text-xl font-bold ${txt}`}>{s.value}</p>
            <p className={`text-[10px] ${sub}`}>{s.label}</p>
          </div>
        ))}
      </div>

      <AnimatePresence>
        {generatedReport && (
          <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className={`rounded-2xl border overflow-hidden ${card}`}>
            <div className={`flex items-center justify-between px-4 py-3 border-b ${dc ? "border-gray-700" : "border-gray-200"}`}>
              <h3 className={`text-sm font-bold ${txt}`}>📋 {u("Report Preview", "رپورٹ کا جائزہ")}</h3>
            </div>
            <pre className={`px-4 py-3 text-xs whitespace-pre-wrap font-mono leading-relaxed max-h-64 overflow-y-auto ${txt} ${dc ? "bg-gray-900/50" : "bg-gray-50"}`}>
              {generatedReport}
            </pre>
            <div className="flex gap-2 p-3 flex-wrap">
              <motion.button whileTap={{ scale: 0.95 }} onClick={sendWhatsApp} className={`${bigBtn} flex-1 bg-green-600 text-white !py-3 !min-h-[48px]`}>
                <Send className="w-4 h-4" /> WhatsApp
              </motion.button>
              <motion.button whileTap={{ scale: 0.95 }} onClick={downloadReport} className={`${bigBtn} flex-1 bg-blue-600 text-white !py-3 !min-h-[48px]`}>
                <FileDown className="w-4 h-4" /> {u("Download", "ڈاؤنلوڈ")}
              </motion.button>
              <motion.button whileTap={{ scale: 0.95 }} onClick={copyReport}
                className={`${bigBtn} flex-1 !py-3 !min-h-[48px] ${dc ? "bg-gray-700 text-gray-200" : "bg-gray-200 text-gray-700"}`}>
                <Clipboard className="w-4 h-4" /> {u("Copy", "کاپی")}
              </motion.button>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {reportHistory.length > 0 && (
        <div className={`rounded-xl border ${card} overflow-hidden`}>
          <div className={`px-4 py-3 border-b ${dc ? "border-gray-700" : "border-gray-200"}`}>
            <h3 className={`text-sm font-bold ${txt}`}>📄 {u("Report History (Last 30 Days)", "رپورٹ کی تاریخ (آخری 30 دن)")}</h3>
          </div>
          <div className="max-h-40 overflow-y-auto">
            {reportHistory.map((r: any) => (
              <div key={r.id} className={`flex items-center gap-3 px-4 py-2.5 border-b ${dc ? "border-gray-700/50" : "border-gray-100"}`}>
                <FileDown className={`w-4 h-4 ${sub}`} />
                <span className={`text-xs font-medium ${txt}`}>{r.date}</span>
                <span className={`text-[10px] px-2 py-0.5 rounded ${dc ? "bg-gray-700 text-gray-400" : "bg-gray-100 text-gray-500"}`}>{r.type}</span>
                <span className={`text-[10px] font-mono ml-auto ${sub}`}>{r.id}</span>
              </div>
            ))}
          </div>
        </div>
      )}
    </motion.div>
  );
}
