import type { Case } from "./mockData";

export function mapSupabaseCaseToLocal(raw: any, profile?: { id?: string; full_name?: string | null; email?: string | null } | null): Case {
  const meta = (raw.metadata || {}) as any;
  return {
    id: raw.case_number || raw.id,
    customerId: raw.client_id || meta.customerId || profile?.id || "",
    customerName: meta.customerName || profile?.full_name || "Customer",
    fatherName: meta.fatherName || "",
    phone: meta.phone || "",
    email: meta.email || profile?.email || "",
    cnic: meta.cnic || "",
    passport: meta.passport || "",
    country: raw.destination_country || meta.country || "",
    jobType: meta.jobType || raw.visa_type || "",
    jobDescription: meta.jobDescription || "",
    address: meta.address || "",
    city: meta.city || "",
    maritalStatus: meta.maritalStatus || "single",
    dateOfBirth: meta.dateOfBirth || "",
    emergencyContact: meta.emergencyContact || { name: "", phone: "", relationship: "" },
    education: meta.education || "",
    experience: meta.experience || "",
    status: raw.status || meta.status || "new_case",
    agentId: raw.agent_id || meta.agentId || "",
    agentName: meta.agentName || "",
    createdDate: raw.created_at || meta.createdDate || new Date().toISOString(),
    updatedDate: raw.updated_at || meta.updatedDate || new Date().toISOString(),
    timeline: meta.timeline || [],
    documents: meta.documents || [],
    payments: meta.payments || [],
    medical: meta.medical || null,
    notes: meta.notes || [],
    priority: (raw.priority || meta.priority || "medium") as any,
    totalFee: meta.totalFee || 0,
    paidAmount: meta.paidAmount || 0,
    pipelineType: meta.pipelineType || "visa",
    pipelineStageKey: raw.status || meta.pipelineStageKey || "new_case",
    previousPipelineType: meta.previousPipelineType,
    migratedAt: meta.migratedAt,
    currentStage: meta.currentStage || 1,
    stageStartedAt: meta.stageStartedAt || raw.created_at || new Date().toISOString(),
    stageDeadlineAt: meta.stageDeadlineAt || raw.created_at || new Date().toISOString(),
    isOverdue: meta.isOverdue || false,
    delayReason: meta.delayReason,
    delayReportedAt: meta.delayReportedAt,
    documentChecklist: meta.documentChecklist || {},
    documentChecklistFiles: meta.documentChecklistFiles || {},
    paymentVerified: meta.paymentVerified || false,
    paymentVerifiedAt: meta.paymentVerifiedAt,
    paymentVerifiedBy: meta.paymentVerifiedBy,
    sirAtifApproval: meta.sirAtifApproval || false,
    sirAtifApprovalAt: meta.sirAtifApprovalAt,
    sirAtifApprovalNote: meta.sirAtifApprovalNote,
    cancellationReason: meta.cancellationReason,
    cancelledAt: meta.cancelledAt,
    cancelledBy: meta.cancelledBy,
    reopenedAt: meta.reopenedAt,
    reopenedBy: meta.reopenedBy,
    reopenedFromStage: meta.reopenedFromStage,
    assignedStaffId: meta.assignedStaffId,
    assignedStaffName: meta.assignedStaffName,
    assignedAt: meta.assignedAt,
    companyName: meta.companyName,
    companyCountry: meta.companyCountry,
  } as Case;
}
